import type { Metadata } from "next";
import "./globals.css";

import Header from "@/layout/header/Header";
import Footer from "@/layout/Footer/Footer";

export const metadata: Metadata = {
  title: "NextSolve - WebSite Official",
  description: "Generated by create next app",
  icons: {
    icon: '/logo.png'
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR" className={``}>
      <Header />
      <body className="min-h-full flex flex-col">{children}</body>
      <Footer />
    </html>
  );
}
